"""add_email_groups

Revision ID: 04e010385047
Revises: 0b54c2166d76
Create Date: 2026-02-18 14:16:00.994097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04e010385047'
down_revision: Union[str, Sequence[str], None] = '0b54c2166d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_groups_id'), 'email_groups', ['id'], unique=False)
    op.create_index(op.f('ix_email_groups_name'), 'email_groups', ['name'], unique=True)
    op.create_table('email_group_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['email_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_group_members_email'), 'email_group_members', ['email'], unique=False)
    op.create_index(op.f('ix_email_group_members_group_id'), 'email_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_email_group_members_id'), 'email_group_members', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_group_members_id'), table_name='email_group_members')
    op.drop_index(op.f('ix_email_group_members_group_id'), table_name='email_group_members')
    op.drop_index(op.f('ix_email_group_members_email'), table_name='email_group_members')
    op.drop_table('email_group_members')
    op.drop_index(op.f('ix_email_groups_name'), table_name='email_groups')
    op.drop_index(op.f('ix_email_groups_id'), table_name='email_groups')
    op.drop_table('email_groups')
    # ### end Alembic commands ###
